import { createContext, useContext, useEffect, useMemo, useState, type ReactNode } from 'react';

export type Language = 'en' | 'it';

const italian: Record<string, string> = {
  'Home': 'Home',
  'Gallery': 'Galleria',
  'What We Do': 'Cosa Facciamo',
  'Contact': 'Contatti',
  'Book a Tattoo': 'Prenota un Tatuaggio',
  'Menu': 'Menu',
  'Close': 'Chiudi',
  'Open menu': 'Apri menu',
  'Close menu': 'Chiudi menu',
  'Navigate the studio': 'Esplora lo studio',
  'Patong · Phuket · Thailand': 'Patong · Phuket · Thailandia',
  'Joker Tattoo home': 'Home di Joker Tattoo',
  'Original tattoo work in the heart of Patong, Phuket.': 'Tatuaggi originali nel cuore di Patong, Phuket.',
  'Visit': 'Dove siamo',
  'Contact Us': 'Contattaci',
  'Follow': 'Seguici',
  'Footer navigation': 'Navigazione a piè di pagina',
  'Joker Tattoo business information': 'Informazioni su Joker Tattoo',
  'Social links to be confirmed': 'Link social da confermare',
  'Start a project': 'Inizia un progetto',
  'Prototype.': 'Prototipo.',
  'Patong, Phuket — exact studio address to be confirmed': 'Patong, Phuket — indirizzo esatto dello studio da confermare',
  'Phone / WhatsApp to be confirmed': 'Telefono / WhatsApp da confermare',
  'Email address to be confirmed': 'Indirizzo email da confermare',
  'Opening hours to be confirmed': 'Orari di apertura da confermare',
  '91 Nanai Rd, Tambon Patong, Amphoe Kathu, Chang Wat Phuket 83150': '91 Nanai Rd, Tambon Patong, Amphoe Kathu, Chang Wat Phuket 83150',
  'Monday – Sunday, 1:00 PM – 8:00 PM': 'Lunedì – Domenica, 13:00 – 20:00',
  'Open Joker Tattoo in Google Maps': 'Apri Joker Tattoo su Google Maps',
  'Patong · Phuket · Custom tattoo studio': 'Patong · Phuket · Studio di tatuaggi personalizzati',
  'Wear your story.': 'Indossa la tua storia.',
  'Leave your mark.': 'Lascia il tuo segno.',
  'Custom tattoo work created in the heart of Patong, Phuket.': 'Tatuaggi personalizzati creati nel cuore di Patong, Phuket.',
  'Explore Our Work': 'Esplora i Nostri Lavori',
  'Scroll to discover': 'Scorri per scoprire',
  'Concept / Craft / Commitment': 'Idea / Arte / Dedizione',
  'A mark made personal': 'Un segno personale',
  'Not decoration.': 'Non decorazione.',
  'A piece of you.': 'Una parte di te.',
  'We approach every tattoo as a collaboration—built around your idea, your body and the way you want to carry it.': 'Ogni tatuaggio nasce da una collaborazione, costruita intorno alla tua idea, al tuo corpo e al modo in cui vuoi portarlo.',
  'Discover the studio': 'Scopri lo studio',
  'Ways to make a mark': 'Modi di lasciare il segno',
  'Styles with intent.': 'Stili con intenzione.',
  'Provisional categories for the first visual template.': 'Categorie provvisorie per il primo prototipo visivo.',
  'Hygiene & Safety': 'Igiene e Sicurezza',
  'Your Safety Comes First': 'La Tua Sicurezza Prima di Tutto',
  'At Joker Tattoo, every tattoo is performed using strict hygiene protocols, professional equipment and single-use sterile supplies to ensure a safe, clean and comfortable experience.': 'Da Joker Tattoo, ogni tatuaggio viene eseguito seguendo rigorosi protocolli igienici, con attrezzature professionali e materiali sterili monouso, per garantire un’esperienza sicura, pulita e confortevole.',
  'Tattoo artist wearing protective gloves while preparing professional equipment': 'Tatuatore con guanti protettivi mentre prepara l’attrezzatura professionale',
  'Joker Tattoo artist working in a professional hygiene and safety focused studio': 'Artista di Joker Tattoo al lavoro in uno studio professionale dedicato a igiene e sicurezza',
  'Professional standards': 'Standard professionali',
  'Clean. Precise. Considered.': 'Pulito. Preciso. Curato.',
  'Single-Use Sterile Needles': 'Aghi Sterili Monouso',
  'Every needle is opened in front of the client and disposed of immediately after use.': 'Ogni ago viene aperto davanti al cliente e smaltito immediatamente dopo l’uso.',
  'Disposable Protective Equipment': 'Dispositivi di Protezione Monouso',
  'Fresh gloves, disposable materials and protective barriers are used throughout every tattoo session.': 'Guanti nuovi, materiali monouso e barriere protettive vengono utilizzati durante ogni sessione di tatuaggio.',
  'Medical-Grade Sterilisation': 'Sterilizzazione di Grado Medicale',
  'Our studio follows professional sterilisation procedures and maintains a clean working environment.': 'Il nostro studio segue procedure professionali di sterilizzazione e mantiene un ambiente di lavoro pulito.',
  'Premium Tattoo Inks': 'Inchiostri Premium',
  'We use high-quality professional inks chosen for their safety, colour vibrancy and long-lasting results.': 'Utilizziamo inchiostri professionali di alta qualità scelti per sicurezza, brillantezza dei colori e durata.',
  'Experienced Artists': 'Artisti Esperti',
  'Our artists combine years of experience with precision and attention to detail to deliver exceptional tattoos safely.': 'I nostri artisti uniscono anni di esperienza, precisione e attenzione ai dettagli per realizzare tatuaggi eccezionali in sicurezza.',
  'Every client receives clear aftercare instructions to help their tattoo heal beautifully and maintain its quality.': 'Ogni cliente riceve chiare istruzioni per la cura, per favorire una guarigione ottimale e preservare la qualità del tatuaggio.',
  'Speak with the studio': 'Parla con lo studio',
  'Still have questions about the tattoo process or hygiene?': 'Hai ancora domande sul processo o sull’igiene?',
  'Our artists are happy to answer any questions before your appointment.': 'I nostri artisti saranno felici di rispondere a ogni domanda prima del tuo appuntamento.',
  'Selected work': 'Lavori selezionati',
  'Built for the body.': 'Creati per il corpo.',
  'View full gallery': 'Vedi la galleria completa',
  'Explore our tattoo gallery': 'Esplora la nostra galleria di tatuaggi',
  'Discuss your tattoo idea': 'Parlaci della tua idea per il tatuaggio',
  'Discuss this tattoo service': 'Parla con noi di questo servizio',
  'Have a direction in mind? Tell the studio about your idea.': 'Hai già una direzione in mente? Racconta la tua idea allo studio.',
  'The studio experience': 'L’esperienza in studio',
  'From first thought to final line.': 'Dalla prima idea alla linea finale.',
  'Your idea starts here': 'La tua idea inizia qui',
  'Ready to make': 'Pronto a renderlo',
  'it permanent?': 'permanente?',
  'Atmospheric tattoo studio interior': 'Interno suggestivo di uno studio di tatuaggi',
  'Tattoo artist preparing a custom design': 'Tatuatore che prepara un design personalizzato',
  'The work': 'I lavori',
  'Every piece has a pulse.': 'Ogni opera ha un battito.',
  'A first look at the visual direction. Final portfolio photography will replace these original prototype assets.': 'Una prima visione della direzione creativa. Le fotografie definitive del portfolio sostituiranno queste immagini prototipo.',
  'Filter gallery': 'Filtra la galleria',
  'All': 'Tutti',
  'Colour': 'Colore',
  'Botanical flow': 'Flusso botanico',
  'Japanese movement': 'Movimento giapponese',
  'The design table': 'Il tavolo da disegno',
  'Ornamental study': 'Studio ornamentale',
  'Body composition': 'Composizione sul corpo',
  'Mark making': 'Creazione del segno',
  'Soft contrast': 'Contrasto morbido',
  'Built to flow': 'Creato per fluire',
  'Close image viewer': 'Chiudi visualizzatore',
  'Previous image': 'Immagine precedente',
  'Next image': 'Immagine successiva',
  'Gallery image viewer': 'Visualizzatore della galleria',
  'What we do': 'Cosa facciamo',
  'Your idea.': 'La tua idea.',
  'Our craft.': 'La nostra arte.',
  'Custom work with the patience, planning and precision it deserves.': 'Lavori personalizzati con la pazienza, la progettazione e la precisione che meritano.',
  'Large Japanese-inspired custom backpiece': 'Grande tatuaggio personalizzato sulla schiena di ispirazione giapponese',
  'Tattoo services': 'Servizi di tatuaggio',
  'No templates. No shortcuts.': 'Niente modelli. Niente scorciatoie.',
  'How it works': 'Come funziona',
  'A considered process.': 'Un processo studiato.',
  'Before you begin': 'Prima di iniziare',
  'Common questions.': 'Domande frequenti.',
  'Start the conversation': 'Inizia la conversazione',
  'Bring us the idea.': 'Portaci la tua idea.',
  'We’ll find the form.': 'Noi le daremo forma.',
  'Plan your tattoo': 'Progetta il tuo tatuaggio',
  'Contact / Booking': 'Contatti / Prenotazioni',
  'Let’s make': 'Creiamo',
  'something permanent.': 'qualcosa di permanente.',
  'Tell us what you have in mind. The more context you share, the better the first conversation can be.': 'Raccontaci cosa hai in mente. Più dettagli condividi, migliore sarà la prima conversazione.',
  'Find us': 'Dove trovarci',
  'Talk to us': 'Parla con noi',
  'Studio hours': 'Orari dello studio',
  'Google Maps embed ready': 'Pronto per Google Maps',
  'Exact location to be confirmed': 'Posizione esatta da confermare',
  'Tell us about your idea.': 'Raccontaci la tua idea.',
  'Name': 'Nome',
  'Email': 'Email',
  'Phone or WhatsApp': 'Telefono o WhatsApp',
  'Preferred artist': 'Artista preferito',
  'No preference / to be confirmed': 'Nessuna preferenza / da confermare',
  'Tattoo style': 'Stile del tatuaggio',
  'Select a direction': 'Scegli una direzione',
  'Not sure yet': 'Non sono ancora sicuro',
  'Placement': 'Posizione sul corpo',
  'Approximate size': 'Dimensione approssimativa',
  'e.g. palm-sized, half sleeve': 'es. grande come il palmo, mezza manica',
  'Preferred date': 'Data preferita',
  'Describe your idea': 'Descrivi la tua idea',
  'Image references': 'Immagini di riferimento',
  'Drop files here or choose images': 'Trascina qui i file o scegli le immagini',
  'Interface only — files are not uploaded in this prototype.': 'Solo interfaccia — i file non vengono caricati in questo prototipo.',
  'I consent to being contacted about this enquiry.': 'Acconsento a essere contattato in merito a questa richiesta.',
  'Review enquiry': 'Controlla la richiesta',
  'Page Not Found': 'Pagina non trovata',
  'Wrong turn.': 'Strada sbagliata.',
  'Let’s get you back.': 'Torniamo indietro.',
  'The page you requested does not exist. Return home, explore the gallery or start a conversation with the studio.': 'La pagina richiesta non esiste. Torna alla home, esplora la galleria o inizia una conversazione con lo studio.',
  'Back to Home': 'Torna alla Home',
  'Explore the Gallery': 'Esplora la Galleria',
  'Contact the Studio': 'Contatta lo Studio',
  'This field is required.': 'Questo campo è obbligatorio.',
  'Enter a valid email address.': 'Inserisci un indirizzo email valido.',
  'Please confirm consent before continuing.': 'Conferma il consenso prima di continuare.',
  'Please check the highlighted fields.': 'Controlla i campi evidenziati.',
  'Prototype only — form delivery and image upload will be connected in a future backend step. Nothing has been submitted.': 'Solo prototipo — l’invio del modulo e il caricamento delle immagini saranno collegati in un futuro aggiornamento del backend. Nessun dato è stato inviato.',
  'Realism': 'Realismo',
  'Black & Grey': 'Nero e Grigio',
  'Traditional': 'Tradizionale',
  'Japanese': 'Giapponese',
  'Fine Line': 'Linea Sottile',
  'Custom Designs': 'Design Personalizzati',
  'Depth, texture and striking detail.': 'Profondità, texture e dettagli d’impatto.',
  'Controlled contrast with a timeless edge.': 'Contrasto controllato dal carattere senza tempo.',
  'Bold forms built to hold their presence.': 'Forme decise create per mantenere la loro presenza.',
  'Flowing compositions designed for the body.': 'Composizioni fluide progettate per il corpo.',
  'Quiet precision and delicate detail.': 'Precisione discreta e dettagli delicati.',
  'Original work developed around your story.': 'Lavori originali sviluppati intorno alla tua storia.',
  'Discover style': 'Scopri lo stile',
  'Custom Tattoos': 'Tatuaggi Personalizzati',
  'Tattoo Consultations': 'Consulenze per Tatuaggi',
  'Cover-Ups': 'Cover-Up',
  'Tattoo Redesign': 'Restyling di Tatuaggi',
  'Fine Line Work': 'Tatuaggi Fine Line',
  'Large-Scale Pieces': 'Tatuaggi di Grandi Dimensioni',
  'Aftercare Guidance': 'Indicazioni per la Cura',
  'One-of-one concepts shaped around your idea, placement and personal style.': 'Concept unici sviluppati intorno alla tua idea, alla posizione e al tuo stile personale.',
  'A focused conversation to define the direction before design begins.': 'Una conversazione mirata per definire la direzione prima di iniziare il design.',
  'Thoughtful options for transforming an existing piece.': 'Soluzioni studiate per trasformare un tatuaggio esistente.',
  'Reworking older tattoos with a stronger, more intentional composition.': 'Rielaborazione di vecchi tatuaggi con una composizione più forte e intenzionale.',
  'Refined linework with attention to spacing, balance and scale.': 'Linee raffinate con attenzione a spaziatura, equilibrio e proporzioni.',
  'Cohesive sleeves, backs and multi-session projects planned as a whole.': 'Maniche, schiene e progetti su più sessioni pianificati come un insieme.',
  'Clear studio guidance to help you care for your new tattoo.': 'Indicazioni chiare dello studio per prenderti cura del tuo nuovo tatuaggio.',
  'Tell us your idea': 'Raccontaci la tua idea',
  'Develop the design': 'Sviluppiamo il design',
  'Tattoo session': 'Sessione di tatuaggio',
  'Healing & aftercare': 'Guarigione e cura',
  'Bring references, a rough thought or simply a feeling.': 'Porta riferimenti, un’idea approssimativa o semplicemente una sensazione.',
  'We shape the concept for your body and direction.': 'Diamo forma al concept in base al tuo corpo e alla tua direzione.',
  'Settle in while the work becomes permanent.': 'Mettiti comodo mentre il lavoro diventa permanente.',
  'Leave with clear, practical studio guidance.': 'Vai via con indicazioni chiare e pratiche dello studio.',
  'Do I need an appointment?': 'Ho bisogno di un appuntamento?',
  'How should I prepare?': 'Come devo prepararmi?',
  'How much will my tattoo cost?': 'Quanto costerà il mio tatuaggio?',
  'Can you redesign or cover an old tattoo?': 'Potete ridisegnare o coprire un vecchio tatuaggio?',
  'What aftercare is required?': 'Quale cura è necessaria?',
  'Appointments are recommended. Walk-in availability can vary, so contacting the studio first is the best starting point.': 'Gli appuntamenti sono consigliati. La disponibilità per i walk-in può variare, quindi contattare prima lo studio è il modo migliore per iniziare.',
  'Arrive rested, hydrated and having eaten. We will share any project-specific preparation before your session.': 'Arriva riposato, idratato e dopo aver mangiato. Prima della sessione condivideremo eventuali preparazioni specifiche.',
  'Pricing depends on size, placement, detail and time. A consultation lets us provide a more useful estimate.': 'Il prezzo dipende da dimensioni, posizione, dettaglio e tempo. Una consulenza ci permette di fornire una stima più utile.',
  'Many existing pieces can be reworked or covered. We need to see the tattoo and discuss realistic options first.': 'Molti tatuaggi esistenti possono essere rielaborati o coperti. Dobbiamo prima vedere il tatuaggio e discutere opzioni realistiche.',
  'Your artist will provide care guidance suited to your tattoo. Contact the studio if anything is unclear.': 'Il tuo artista fornirà indicazioni adatte al tuo tatuaggio. Contatta lo studio se qualcosa non è chiaro.',
};

type LanguageContextValue = {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (text: string) => string;
};

const LanguageContext = createContext<LanguageContextValue | null>(null);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>(() => localStorage.getItem('joker-language') === 'it' ? 'it' : 'en');

  useEffect(() => {
    localStorage.setItem('joker-language', language);
    document.documentElement.lang = language;
  }, [language]);

  const value = useMemo(() => ({
    language,
    setLanguage,
    t: (text: string) => language === 'it' ? (italian[text] ?? text) : text,
  }), [language]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

// The provider and its colocated hook form one small application-level API.
// eslint-disable-next-line react-refresh/only-export-components
export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used inside LanguageProvider');
  return context;
}
