import { createContext, useContext, useEffect, useMemo, useState, type ReactNode } from 'react';

export type Language = 'en' | 'it';

const italian: Record<string, string> = {
  'Home': 'Home',
  'Gallery': 'Galleria',
  'Why Joker': 'Perché Joker',
  'Contact': 'Contatti',
  'Book a Tattoo': 'Prenota il tuo tatuaggio',
  'Menu': 'Menu',
  'Close': 'Chiudi',
  'Open menu': 'Apri menu',
  'Close menu': 'Chiudi menu',
  'Navigate the studio': 'Esplora lo studio',
  'Patong · Phuket · Thailand': 'Patong · Phuket · Thailandia',
  'Joker Tattoo home': 'Home di Joker Tattoo',
  'Joker Tattoo Patong studio logo': 'Logo dello studio Joker Tattoo Patong',
  'Joker Tattoo Patong studio wordmark': 'Logo testuale dello studio Joker Tattoo Patong',
  'Joker Tattoo portfolio gallery': 'Galleria portfolio di Joker Tattoo',
  'View': 'Guarda il',
  'tattoo portfolio': 'portfolio di tatuaggi',
  'Original tattoo work in the heart of Patong, Phuket.': 'Tatuaggi originali nel cuore di Patong, Phuket.',
  'Visit': 'Dove siamo',
  'Contact Us': 'Contattaci',
  'Follow': 'Seguici',
  'Footer navigation': 'Navigazione a piè di pagina',
  'Joker Tattoo business information': 'Informazioni su Joker Tattoo',
  'Social links to be confirmed': 'Link social da confermare',
  'Start a project': 'Inizia un progetto',
  'All rights reserved.': 'Tutti i diritti riservati.',
  'Patong, Phuket — exact studio address to be confirmed': 'Patong, Phuket — indirizzo esatto dello studio da confermare',
  'Phone / WhatsApp to be confirmed': 'Telefono / WhatsApp da confermare',
  'Email address to be confirmed': 'Indirizzo email da confermare',
  'Opening hours to be confirmed': 'Orari di apertura da confermare',
  '91 Nanai Rd, Tambon Patong, Amphoe Kathu, Chang Wat Phuket 83150': '91 Nanai Rd, Tambon Patong, Amphoe Kathu, Chang Wat Phuket 83150',
  'Monday – Sunday, 1:00 PM – 8:00 PM': 'Lunedì – Domenica, 13:00 – 20:00',
  'Open Joker Tattoo in Google Maps': 'Apri Joker Tattoo su Google Maps',
  'Interactive map showing Joker Tattoo in Patong': 'Mappa interattiva di Joker Tattoo a Patong',
  'Patong · Phuket · Custom tattoo studio': 'Patong · Phuket · Studio di tatuaggi personalizzati',
  'Traditional tiger Sak Yant tattoo created at Joker Tattoo Patong': 'Tatuaggio Sak Yant tradizionale con tigre realizzato da Joker Tattoo Patong',
  'Japanese backpiece tattoo by Joker Tattoo Patong': 'Backpiece giapponese realizzato da Joker Tattoo Patong',
  'Wear your story.': 'La tua storia sulla pelle.',
  'Leave your mark.': 'Lascia il tuo segno.',
  'Custom tattoo work created in the heart of Patong, Phuket.': 'Tatuaggi personalizzati creati nel cuore di Patong, Phuket.',
  'Explore Our Work': 'Scopri i nostri lavori',
  'Scroll to discover': 'Scorri per scoprire',
  'Concept / Craft / Commitment': 'Idea / Tecnica / Dedizione',
  'A mark made personal': 'Un segno che parla di te',
  'Not decoration.': 'Non è solo decorazione.',
  'A piece of you.': 'Una parte di te.',
  'We approach every tattoo as a collaboration—built around your idea, your body and the way you want to carry it.': 'Ogni tatuaggio nasce dal confronto con te: dalla tua idea, dalle forme del tuo corpo e da ciò che vuoi esprimere.',
  'Discover the studio': 'Scopri lo studio',
  'Ways to make a mark': 'Tanti modi di lasciare il segno',
  'Styles with intent.': 'Ogni stile, una scelta precisa.',
  'Provisional categories for the first visual template.': 'Esplora alcuni degli stili che realizziamo in studio.',
  'Hygiene & Safety': 'Igiene e Sicurezza',
  'Your Safety Comes First': 'La tua sicurezza prima di tutto',
  'At Joker Tattoo, every tattoo is performed using strict hygiene protocols, professional equipment and single-use sterile supplies to ensure a safe, clean and comfortable experience.': 'Da Joker Tattoo, ogni tatuaggio viene eseguito seguendo rigorosi protocolli igienici, con attrezzature professionali e materiali sterili monouso, per garantire un’esperienza sicura, pulita e confortevole.',
  'Tattoo artist wearing protective gloves while preparing professional equipment': 'Tatuatore con guanti protettivi mentre prepara l’attrezzatura professionale',
  'Joker Tattoo artist working in a professional hygiene and safety focused studio': 'Tatuatore di Joker Tattoo al lavoro in uno studio professionale, pulito e sicuro',
  'Professional standards': 'Standard professionali',
  'Clean. Precise. Considered.': 'Pulito. Preciso. Curato.',
  'Single-Use Sterile Needles': 'Aghi Sterili Monouso',
  'Every needle is opened in front of the client and disposed of immediately after use.': 'Ogni ago viene aperto davanti al cliente e smaltito immediatamente dopo l’uso.',
  'Disposable Protective Equipment': 'Protezioni monouso',
  'Fresh gloves, disposable materials and protective barriers are used throughout every tattoo session.': 'Guanti nuovi, materiali monouso e barriere protettive vengono utilizzati durante ogni sessione di tatuaggio.',
  'Medical-Grade Sterilisation': 'Sterilizzazione di livello medico',
  'Our studio follows professional sterilisation procedures and maintains a clean working environment.': 'Il nostro studio segue procedure professionali di sterilizzazione e mantiene un ambiente di lavoro pulito.',
  'Premium Tattoo Inks': 'Inchiostri professionali',
  'We use high-quality professional inks chosen for their safety, colour vibrancy and long-lasting results.': 'Utilizziamo inchiostri professionali di alta qualità scelti per sicurezza, brillantezza dei colori e durata.',
  'Experienced Artists': 'Artisti Esperti',
  'Our artists combine years of experience with precision and attention to detail to deliver exceptional tattoos safely.': 'Esperienza, precisione e attenzione ai dettagli ci permettono di realizzare tatuaggi di alta qualità in totale sicurezza.',
  'Every client receives clear aftercare instructions to help their tattoo heal beautifully and maintain its quality.': 'Ogni cliente riceve chiare istruzioni per la cura, per favorire una guarigione ottimale e preservare la qualità del tatuaggio.',
  'Speak with the studio': 'Parla con lo studio',
  'Still have questions about the tattoo process or hygiene?': 'Hai ancora domande sul processo o sull’igiene?',
  'Our artists are happy to answer any questions before your appointment.': 'I nostri artisti saranno felici di rispondere a ogni domanda prima del tuo appuntamento.',
  'Google Reviews': 'Recensioni Google',
  'Stories carried forward.': 'Storie che restano.',
  'What clients say about their experience at Joker Tattoo Patong.': 'Le esperienze di chi ha scelto Joker Tattoo Patong.',
  'Read all Google reviews': 'Leggi tutte le recensioni su Google',
  'Customer Review': 'Recensione cliente',
  'out of 5 stars': 'stelle su 5',
  'Friendly, professional and right in the centre of Patong.': 'Personale cordiale e professionale, proprio nel centro di Patong.',
  'Helpful with ideas, pricing and timing, with a fresh and clean studio.': 'Ci hanno aiutato a definire l’idea, il prezzo e le tempistiche. Lo studio è pulito e accogliente.',
  'A returning client who praises the helpful team and specialist artists.': 'Un cliente abituale che apprezza la disponibilità del team e la competenza degli artisti.',
  'Selected work': 'Lavori selezionati',
  'Built for the body.': 'Creati per il corpo.',
  'View full gallery': 'Vedi la galleria completa',
  'Explore our tattoo gallery': 'Esplora la nostra galleria di tatuaggi',
  'Discuss your tattoo idea': 'Raccontaci la tua idea',
  'Discuss this tattoo service': 'Parlaci del tuo progetto',
  'Have a direction in mind? Tell the studio about your idea.': 'Hai già un’idea? Raccontacela.',
  'The studio experience': 'L’esperienza in studio',
  'From first thought to final line.': 'Dall’idea iniziale all’ultima linea.',
  'Your idea starts here': 'La tua idea inizia qui',
  'Ready to make': 'Pronto a creare',
  'it permanent?': 'qualcosa che resta?',
  'Atmospheric tattoo studio interior': 'Interno suggestivo di uno studio di tatuaggi',
  'Tattoo artist preparing a custom design': 'Tatuatore che prepara un design personalizzato',
  'The work': 'I nostri lavori',
  'Explore tattoo work created by Joker Tattoo in Patong, from Japanese sleeves and realism to traditional Sak Yant.': 'Scopri i tatuaggi realizzati da Joker Tattoo a Patong: sleeve giapponesi, realistici e Sak Yant tradizionali.',
  'Every piece has a pulse.': 'Ogni tatuaggio ha un’anima.',
  'A first look at the visual direction. Final portfolio photography will replace these original prototype assets.': 'Una selezione dei lavori realizzati dai nostri artisti.',
  'Filter gallery': 'Filtra i lavori',
  'All': 'Tutti',
  'Colour': 'Colore',
  'Botanical flow': 'Flusso botanico',
  'Japanese movement': 'Movimento giapponese',
  'The design table': 'Il tavolo da disegno',
  'Ornamental study': 'Studio ornamentale',
  'Body composition': 'Composizione sul corpo',
  'Mark making': 'Creazione del segno',
  'Soft contrast': 'Contrasto morbido',
  'Built to flow': 'Pensato per seguire il corpo',
  'Close image viewer': 'Chiudi il visualizzatore',
  'Previous image': 'Immagine precedente',
  'Next image': 'Immagine successiva',
  'Gallery image viewer': 'Visualizzatore immagini della galleria',
  'Black and grey custom portfolio tattoo by Joker Tattoo Patong': 'Tatuaggio personalizzato black & grey realizzato da Joker Tattoo Patong',
  'Tattoo artist working on a client at Joker Tattoo Patong': 'Tatuatore di Joker Tattoo Patong al lavoro su un cliente',
  'Your idea.': 'La tua idea.',
  'Our craft.': 'La nostra arte.',
  'Custom work with the patience, planning and precision it deserves.': 'Tatuaggi su misura, progettati e realizzati con tutta la cura e la precisione che meritano.',
  'Large Japanese-inspired custom backpiece': 'Grande tatuaggio personalizzato sulla schiena di ispirazione giapponese',
  'Tattoo services': 'Servizi di tatuaggio',
  'No templates. No shortcuts.': 'Niente modelli predefiniti. Nessuna scorciatoia.',
  'A professional consultation turns an early idea into a clear, achievable tattoo plan before any work begins.': 'Una consulenza professionale trasforma un’idea iniziale in un progetto chiaro e realizzabile prima di iniziare il lavoro.',
  'Choose the right direction': 'Scegli la direzione giusta',
  'We help refine the style, placement, scale and composition around your body.': 'Ti aiutiamo a definire stile, posizione, dimensioni e composizione in armonia con il tuo corpo.',
  'Meet the right artist': 'Incontra l’artista giusto',
  'Your project is matched with an experienced artist whose strengths suit the work.': 'Affidiamo il tuo progetto a un artista esperto le cui competenze sono adatte al lavoro.',
  'Plan with confidence': 'Pianifica con sicurezza',
  'You receive clear guidance on timing, pricing, preparation and what happens next.': 'Riceverai indicazioni chiare su tempi, prezzo, preparazione e passaggi successivi.',
  'Why Choose Joker Tattoo': 'Perché scegliere Joker Tattoo',
  'Trusted by travellers and locals.': 'Scelto da viaggiatori e residenti.',
  'Experienced artists, honest guidance, custom design and professional studio standards—right in the heart of Patong.': 'Artisti esperti, consulenza trasparente, design personalizzati e standard professionali nel cuore di Patong.',
  'How it works': 'Come funziona',
  'A considered process.': 'Ogni fase conta.',
  'Before you begin': 'Prima di iniziare',
  'Before you book': 'Prima di prenotare',
  'Frequently Asked Questions': 'Domande frequenti',
  'Everything you need to know before booking your tattoo session at Joker Tattoo Phuket.': 'Tutto ciò che è utile sapere prima di prenotare una sessione da Joker Tattoo Phuket.',
  'Personal guidance': 'Consulenza personale',
  'Still have questions?': 'Hai ancora domande?',
  "We're happy to help. Contact our artists today and we'll guide you through the entire process.": 'Siamo qui per aiutarti. Contatta i nostri artisti: ti accompagneremo in ogni fase, dall’idea alla realizzazione.',
  'WhatsApp Us': 'Scrivici su WhatsApp',
  'Common questions.': 'Domande frequenti.',
  'Start the conversation': 'Parliamone',
  'Bring us the idea.': 'Portaci la tua idea.',
  'We’ll find the form.': 'Insieme le daremo forma.',
  'Plan your tattoo': 'Progetta il tuo tatuaggio',
  'Contact / Booking': 'Contatti / Prenotazioni',
  'Let’s make': 'Creiamo insieme',
  'something permanent.': 'qualcosa che resta.',
  'Tell us what you have in mind. The more context you share, the better the first conversation can be.': 'Raccontaci cosa hai in mente. Più dettagli ci dai, più utile sarà il primo confronto.',
  'Find us': 'Dove trovarci',
  'Talk to us': 'Contattaci',
  'Studio hours': 'Orari dello studio',
  'Google Maps embed ready': 'Pronto per Google Maps',
  'Exact location to be confirmed': 'Posizione esatta da confermare',
  'Tell us about your idea.': 'Raccontaci la tua idea.',
  'Name': 'Nome',
  'Email': 'Email',
  'Phone or WhatsApp': 'Telefono o WhatsApp',
  'Preferred artist': 'Artista preferito',
  'No preference / to be confirmed': 'Nessuna preferenza / da confermare',
  'Tattoo style': 'Stile del tatuaggio',
  'Select a direction': 'Scegli una direzione',
  'Not sure yet': 'Non lo so ancora',
  'Placement': 'Zona del corpo',
  'Approximate size': 'Dimensione approssimativa',
  'e.g. palm-sized, half sleeve': 'es. grande come il palmo, mezza manica',
  'Preferred date': 'Data preferita',
  'Describe your idea': 'Descrivi la tua idea',
  'Image references': 'Immagini di riferimento',
  'Drop files here or choose images': 'Trascina qui i file o scegli le immagini',
  'Interface only — files are not uploaded in this prototype.': 'Solo interfaccia — i file non vengono caricati in questo prototipo.',
  'I consent to being contacted about this enquiry.': 'Acconsento a essere contattato in merito a questa richiesta.',
  'Review enquiry': 'Rivedi la richiesta',
  'Page Not Found': 'Pagina non trovata',
  'Wrong turn.': 'Strada sbagliata.',
  'Let’s get you back.': 'Torniamo indietro.',
  'The page you requested does not exist. Return home, explore the gallery or start a conversation with the studio.': 'La pagina richiesta non esiste. Torna alla home, esplora la galleria o inizia una conversazione con lo studio.',
  'Back to Home': 'Torna alla Home',
  'Explore the Gallery': 'Esplora la Galleria',
  'Contact the Studio': 'Contatta lo Studio',
  'This field is required.': 'Questo campo è obbligatorio.',
  'Enter a valid email address.': 'Inserisci un indirizzo email valido.',
  'Please confirm consent before continuing.': 'Conferma il consenso prima di continuare.',
  'Please check the highlighted fields.': 'Controlla i campi evidenziati.',
  'Prototype only — form delivery and image upload will be connected in a future backend step. Nothing has been submitted.': 'Solo prototipo — l’invio del modulo e il caricamento delle immagini saranno collegati in un futuro aggiornamento del backend. Nessun dato è stato inviato.',
  'Close booking form': 'Chiudi il modulo di prenotazione',
  'Private appointment request': 'Richiesta di appuntamento riservata',
  'Begin your piece.': 'Diamo forma alla tua idea.',
  'Share the essentials. Our team will contact you personally to discuss your idea and confirm availability.': 'Condividi con noi le informazioni principali. Ti contatteremo personalmente per parlare della tua idea e verificare la disponibilità.',
  'Your details': 'I tuoi dati',
  'Your full name': 'Nome e cognome',
  'WhatsApp': 'WhatsApp',
  'Preferred appointment': 'Quando preferisci venire',
  'Preferred Date': 'Data preferita',
  'Preferred Time': 'Orario preferito',
  'This is a request, not an instant booking. We will confirm availability with you.': 'Questa è una richiesta, non una prenotazione immediata. Confermeremo la disponibilità con te.',
  'Your tattoo': 'Il tuo progetto',
  'Tattoo Style': 'Stile del tatuaggio',
  'Estimated Size': 'Dimensione stimata',
  'Select a style (optional)': 'Scegli uno stile (facoltativo)',
  'Select a size (optional)': 'Scegli una dimensione (facoltativo)',
  'References & notes': 'Immagini e dettagli',
  'Add reference images': 'Allega immagini di riferimento',
  'Drag & drop or choose from camera / gallery': 'Trascina qui le immagini oppure sceglile dalla fotocamera o dalla galleria',
  'Selected reference images': 'Immagini di riferimento selezionate',
  'Each image must be 3 MB or smaller.': 'Ogni immagine deve essere di 3 MB o meno.',
  'Remove': 'Rimuovi',
  'Additional Notes': 'Altri dettagli',
  'Tell us about placement, meaning, colours, or anything else we should know.': 'Indicaci la zona del corpo, il significato, i colori o qualsiasi altro dettaglio utile.',
  'Personal review': 'Valutazione personalizzata',
  'Your request goes directly to our studio team.': 'La tua richiesta arriva direttamente al team dello studio.',
  'Request Appointment': 'Invia la richiesta',
  'Sending request…': 'Invio in corso…',
  'Request received': 'Richiesta inviata',
  'Thank you!': 'Grazie!',
  "We've received your booking request.": 'Abbiamo ricevuto la tua richiesta di prenotazione.',
  'Our team will contact you shortly via WhatsApp or email to confirm your appointment.': 'Ti contatteremo a breve tramite WhatsApp o email per confermare l’appuntamento.',
  'Return to Website': 'Torna al sito',
  'Please enter your name.': 'Inserisci il tuo nome.',
  'Please enter a valid email.': 'Inserisci un indirizzo email valido.',
  'Please enter your WhatsApp number.': 'Inserisci il tuo numero WhatsApp.',
  'Please choose a preferred date.': 'Scegli una data preferita.',
  'Please choose a preferred time.': 'Scegli un orario preferito.',
  'Something went wrong. Please try again or contact us directly.': 'Qualcosa è andato storto. Riprova o contattaci direttamente.',
  'Appointment requests': 'Richieste di appuntamento',
  'Your idea starts here.': 'Tutto parte dalla tua idea.',
  'Send your preferred date, time and references through our private booking request. Our team will review everything and reply personally by WhatsApp or email.': 'Indicaci quando preferisci venire e allega le immagini di riferimento. Esamineremo la richiesta e ti risponderemo direttamente tramite WhatsApp o email.',
  'No commitment': 'Senza impegno',
  'Personal studio reply': 'Risposta diretta dallo studio',
  'Reference images welcome': 'Puoi allegare immagini',
  'This is a request only. Your appointment is confirmed after our team contacts you.': 'L’appuntamento sarà effettivo solo dopo la conferma del nostro team.',
  'Small': 'Piccolo',
  'Medium': 'Medio',
  'Large': 'Grande',
  'Full Sleeve': 'Manica intera',
  'Half Sleeve': 'Mezza manica',
  'Back Piece': 'Schiena completa',
  'Leg Sleeve': 'Gamba completa',
  'Chest': 'Petto',
  'Other': 'Altro',
  'Tribal': 'Tribale',
  'Bamboo Tattoo': 'Tatuaggio con bamboo',
  'Cover Up': 'Cover-up',
  'Not Sure Yet': 'Non lo so ancora',
  'Thai Traditional': 'Tradizionale thailandese',
  'Tiger Sak Yant': 'Sak Yant con tigre',
  'Japanese Tiger Sleeves': 'Sleeve giapponesi con tigri',
  'Sacred Geometry': 'Geometria sacra',
  'Thai Warrior': 'Guerriero thailandese',
  'Hannya & Koi': 'Hannya e koi',
  'Oni Sleeves': 'Sleeve con Oni',
  'Daruma Sleeve': 'Sleeve con Daruma',
  'Sacred Backpiece': 'Backpiece Sak Yant',
  'Woman & Rose': 'Donna e rosa',
  'Purple Hannya': 'Hannya viola',
  'Ornamental Mandala': 'Mandala ornamentale',
  'Religious Sleeve': 'Sleeve a tema religioso',
  'Japanese Backpiece': 'Backpiece giapponese',
  'Sak Yant Chest': 'Sak Yant sul petto',
  'Blue Dragon': 'Drago blu',
  'Full Back Sak Yant': 'Sak Yant su tutta la schiena',
  'Portrait Realism': 'Ritratto realistico',
  'Thai Traditional Sleeve': 'Sleeve tradizionale thailandese',
  'Custom Portfolio Piece': 'Tatuaggio personalizzato',
  'Woman Smile Portrait': 'Ritratto di donna sorridente',
  'Polynesian Chest & Shoulder': 'Polinesiano su petto e spalla',
  'Geometric Tribal Leg': 'Tribale geometrico sulla gamba',
  'Thai Guardian': 'Guardiano thailandese',
  'Woman & Rifle': 'Donna con fucile',
  'Japanese Serpent Sleeve': 'Sleeve giapponese con serpente',
  'Traditional tiger Sak Yant tattoo across the back': 'Tatuaggio Sak Yant tradizionale con tigre sulla schiena',
  'Colour Japanese tiger and floral sleeve tattoos': 'Sleeve giapponesi a colori con tigri e fiori',
  'Black and grey sacred geometry chest tattoo': 'Tatuaggio black & grey con geometria sacra sul petto',
  'Detailed black and grey Thai warrior leg tattoo': 'Tatuaggio black & grey dettagliato con guerriero thailandese sulla gamba',
  'Colour Japanese Hannya mask and koi sleeve tattoos': 'Sleeve giapponesi a colori con maschera Hannya e carpe koi',
  'Japanese Oni, peony and koi sleeve tattoos': 'Sleeve giapponesi con Oni, peonie e carpe koi',
  'Japanese guardian and red Daruma full sleeve tattoo': 'Full sleeve giapponese con guardiano e Daruma rosso',
  'Traditional Sak Yant full back tattoo': 'Tatuaggio Sak Yant tradizionale su tutta la schiena',
  'Black and grey realistic woman and rose arm tattoo': 'Tatuaggio realistico black & grey con donna e rosa sul braccio',
  'Purple Japanese Hannya mask colour tattoo': 'Tatuaggio a colori con maschera Hannya viola',
  'Ornamental blackwork mandala tattoo across the upper back': 'Mandala ornamentale blackwork sulla parte alta della schiena',
  'Black and grey religious realism sleeve tattoo': 'Sleeve realistico black & grey a tema religioso',
  'Large-scale Japanese backpiece tattoo by Joker Tattoo Patong': 'Backpiece giapponese di grandi dimensioni realizzato da Joker Tattoo Patong',
  'Traditional Sak Yant chest tattoo by Joker Tattoo Patong': 'Sak Yant tradizionale sul petto realizzato da Joker Tattoo Patong',
  'Vivid blue Japanese dragon sleeve tattoo': 'Sleeve giapponese con drago blu dai colori intensi',
  'Full-back traditional Sak Yant composition': 'Composizione Sak Yant tradizionale su tutta la schiena',
  'Black and grey woman portrait realism tattoo': 'Ritratto realistico black & grey di donna',
  'Thai traditional Ganesha full sleeve tattoo': 'Full sleeve thailandese tradizionale con Ganesha',
  'Custom tattoo work by Joker Tattoo Patong': 'Tatuaggio personalizzato realizzato da Joker Tattoo Patong',
  'Black and grey realistic woman portrait tattoo with theatrical face details': 'Ritratto realistico black & grey di donna con dettagli teatrali sul viso',
  'Polynesian tribal chest and shoulder tattoo shown from three angles': 'Tatuaggio tribale polinesiano su petto e spalla visto da tre angolazioni',
  'Geometric ornamental tribal leg tattoo shown from three angles': 'Tatuaggio tribale geometrico ornamentale sulla gamba visto da tre angolazioni',
  'Detailed traditional Thai guardian tattoo on the lower leg': 'Tatuaggio dettagliato con guardiano thailandese tradizionale sulla parte bassa della gamba',
  'Black and grey realistic woman portrait with rifle tattoo': 'Ritratto realistico black & grey di donna con fucile',
  'Black and grey Japanese serpent and floral full sleeve tattoo': 'Full sleeve giapponese black & grey con serpente e fiori',
  'Realism': 'Realismo',
  'Black & Grey': 'Black & Grey',
  'Traditional': 'Tradizionale',
  'Japanese': 'Giapponese',
  'Fine Line': 'Fine line',
  'Custom Designs': 'Progetti su misura',
  'Depth, texture and striking detail.': 'Profondità, texture e dettagli d’impatto.',
  'Controlled contrast with a timeless edge.': 'Contrasti calibrati, dal carattere intramontabile.',
  'Bold forms built to hold their presence.': 'Forme decise, pensate per durare.',
  'Flowing compositions designed for the body.': 'Composizioni fluide progettate per il corpo.',
  'Quiet precision and delicate detail.': 'Linee precise e dettagli delicati.',
  'Original work developed around your story.': 'Progetti originali costruiti intorno alla tua storia.',
  'Discover style': 'Scopri lo stile',
  'Custom Tattoos': 'Tatuaggi personalizzati',
  'Tattoo Consultations': 'Consulenze per tatuaggi',
  'Cover-Ups': 'Cover-Up',
  'Tattoo Redesign': 'Restyling di tatuaggi',
  'Fine Line Work': 'Tatuaggi fine line',
  'Large-Scale Pieces': 'Tatuaggi di grandi dimensioni',
  'Aftercare Guidance': 'Indicazioni per la cura',
  'One-of-one concepts shaped around your idea, placement and personal style.': 'Progetti unici, sviluppati a partire dalla tua idea, dalla zona del corpo e dal tuo stile.',
  'A focused conversation to define the direction before design begins.': 'Una conversazione mirata per definire la direzione prima di iniziare il design.',
  'Thoughtful options for transforming an existing piece.': 'Soluzioni studiate per trasformare un tatuaggio esistente.',
  'Reworking older tattoos with a stronger, more intentional composition.': 'Rielaboriamo i vecchi tatuaggi con composizioni più solide, equilibrate e consapevoli.',
  'Refined linework with attention to spacing, balance and scale.': 'Linee precise, con grande attenzione a spazi, equilibrio e proporzioni.',
  'Cohesive sleeves, backs and multi-session projects planned as a whole.': 'Sleeve, backpiece e lavori in più sedute, progettati fin dall’inizio come un’unica composizione.',
  'Clear studio guidance to help you care for your new tattoo.': 'Ti diamo indicazioni chiare per prenderti cura del tuo nuovo tatuaggio.',
  'Tell us your idea': 'Raccontaci la tua idea',
  'Develop the design': 'Sviluppiamo il progetto',
  'tattoo style portfolio image': 'immagine dello stile nel portfolio',
  'Tattoo session': 'Sessione di tatuaggio',
  'Healing & aftercare': 'Guarigione e cura',
  'Bring references, a rough thought or simply a feeling.': 'Porta con te immagini, uno spunto o anche solo una sensazione da cui partire.',
  'We shape the concept for your body and direction.': 'Sviluppiamo il progetto perché si adatti al tuo corpo e allo stile che cerchi.',
  'Settle in while the work becomes permanent.': 'Rilassati: la tua idea prende vita sulla pelle.',
  'Leave with clear, practical studio guidance.': 'Al termine riceverai indicazioni chiare e pratiche per la cura del tatuaggio.',
  'How do I get to Joker Tattoo in Patong?': 'Come posso raggiungere Joker Tattoo a Patong?',
  'Contact us before your visit and we will send you the studio location and the clearest directions from where you are staying in Patong or elsewhere in Phuket.': 'Contattaci prima di venire: ti invieremo la posizione dello studio e le indicazioni più semplici per raggiungerci, da Patong o da qualsiasi altra zona di Phuket.',
  'Do I need to book an appointment or can I walk in?': 'Devo prenotare o posso venire senza appuntamento?',
  'Appointments are recommended so we can give your idea the right artist, preparation and time. Walk-in availability varies, so contacting the studio first is always the best starting point.': 'Ti consigliamo di prenotare, così possiamo affidare il progetto all’artista più adatto e dedicargli il tempo necessario. La disponibilità per chi arriva senza appuntamento varia: contattaci prima di passare.',
  'How should I prepare before getting a tattoo?': 'Come devo prepararmi prima del tatuaggio?',
  'Arrive well rested, hydrated and having eaten a proper meal. Avoid alcohol before your appointment, wear comfortable clothing that gives easy access to the placement, and follow any project-specific guidance from your artist.': 'Riposa bene, idratati e fai un pasto completo prima dell’appuntamento. Evita l’alcol, indossa abiti comodi che lascino libera la zona da tatuare e segui le indicazioni specifiche del tuo artista.',
  'What is the recommended tattoo aftercare?': 'Come devo prendermi cura del tatuaggio?',
  'Your artist will provide clear aftercare instructions suited to your tattoo and skin. Follow those directions carefully, keep the area clean, and contact the studio if anything about the healing process is unclear.': 'Il tuo artista ti darà istruzioni precise, adatte al tatuaggio e alla tua pelle. Seguile con attenzione, mantieni pulita la zona e contatta lo studio se hai dubbi durante la guarigione.',
  'What is the difference between Machine and Bamboo Tattoos?': 'Qual è la differenza tra tatuaggio a macchinetta e bamboo tattoo?',
  'Machine tattooing uses an electric tattoo machine for precise, consistent lining, shading and colour work. Bamboo tattooing is applied by hand with a traditional tool and offers a different rhythm and finish. The best method depends on your design, placement and preferred result, and our artists can guide you.': 'La macchinetta elettrica permette linee, sfumature e colori precisi e uniformi. Il bamboo tattoo, invece, viene eseguito a mano con uno strumento tradizionale e offre un ritmo e una resa differenti. La tecnica più adatta dipende dal disegno, dalla zona del corpo e dal risultato che desideri: i nostri artisti sapranno consigliarti.',
  'How much does a tattoo cost?': 'Quanto costa un tatuaggio?',
  'Pricing depends on the size, placement, level of detail, style and time required. Share your idea with us and a consultation will allow the studio to provide a useful estimate before you book.': 'Il prezzo dipende dalle dimensioni, dalla zona del corpo, dallo stile, dal livello di dettaglio e dal tempo necessario. Raccontaci la tua idea: dopo un primo confronto potremo darti una stima prima della prenotazione.',
  'Do I need an appointment?': 'È necessario prenotare?',
  'How should I prepare?': 'Come devo prepararmi?',
  'How much will my tattoo cost?': 'Quanto costerà il mio tatuaggio?',
  'Can you redesign or cover an old tattoo?': 'Potete ridisegnare o coprire un vecchio tatuaggio?',
  'What aftercare is required?': 'Come devo prendermi cura del tatuaggio?',
  'Appointments are recommended. Walk-in availability can vary, so contacting the studio first is the best starting point.': 'È consigliabile prenotare. La disponibilità senza appuntamento può variare, quindi contattaci prima di passare in studio.',
  'Arrive rested, hydrated and having eaten. We will share any project-specific preparation before your session.': 'Riposa bene, idratati e mangia prima di venire. Ti comunicheremo in anticipo eventuali indicazioni specifiche per il tuo progetto.',
  'Pricing depends on size, placement, detail and time. A consultation lets us provide a more useful estimate.': 'Il prezzo dipende dalle dimensioni, dalla zona del corpo, dal livello di dettaglio e dal tempo necessario. Dopo un primo confronto potremo darti una stima più precisa.',
  'Many existing pieces can be reworked or covered. We need to see the tattoo and discuss realistic options first.': 'Molti tatuaggi possono essere rivisti o coperti. Prima dobbiamo vedere il lavoro esistente e valutare insieme le soluzioni possibili.',
  'Your artist will provide care guidance suited to your tattoo. Contact the studio if anything is unclear.': 'Il tatuatore ti darà tutte le indicazioni necessarie per la cura. Se hai dubbi, contatta lo studio.',
};

type LanguageContextValue = {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (text: string) => string;
};

const LanguageContext = createContext<LanguageContextValue | null>(null);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>(() => localStorage.getItem('joker-language') === 'it' ? 'it' : 'en');

  useEffect(() => {
    localStorage.setItem('joker-language', language);
    document.documentElement.lang = language;
  }, [language]);

  const value = useMemo(() => ({
    language,
    setLanguage,
    t: (text: string) => language === 'it' ? (italian[text] ?? text) : text,
  }), [language]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

// The provider and its colocated hook form one small application-level API.
// eslint-disable-next-line react-refresh/only-export-components
export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used inside LanguageProvider');
  return context;
}
